### ISSUE TITLE
Add Ada

### ISSUE THREAD

**Issue by rikardn** [madnight/githut#111]
Could perhaps Ada be added to the list of languages? It is currently #23 on TIOBE and #15 on pypl.

**Comment by madnight** [comment]
Hi @rikardn, I do not add languages to the ranking, the ranking is automatically generated from the data. So if ADA is currently not in the top 50 on GitHub for the last quarter, then it does not show up in the ranking.

**Comment by rikardn** [comment]
Ok, thanks for explaining.
