### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by 3052** [madnight/githut#114]
https://github.com/madnight/githut#manual

https://cloud.google.com/bigquery/public-data/github

**Comment by madnight** [comment]
The link is currently working for me. Maybe a temporary issue?

**Comment by 3052** [comment]
if you go to this site:
https://cloud.google.com/bigquery/public-data/github

it redirects here:
https://cloud.google.com/bigquery/public-data

you should provide an updated link to the GitHub data, if one exists

**Comment by madnight** [comment]
Done https://github.com/madnight/githut/commit/27cec55cd331c666e37e71d7d25635c417f2ab43
