### ISSUE TITLE
Q3 2024 Update

### ISSUE THREAD

**Issue by serdar-irmak** [madnight/githut#119]
Hi, can you please add Q3 2024 update, and why is these graphs so different from https://innovationgraph.github.com/global-metrics/programming-languages ?

**Comment by madnight** [comment]
Hi @serdar-irmak,

there is a Problem with the upstream dataset:

![image](https://github.com/user-attachments/assets/ef720ac6-fb7f-4b1d-b779-a19ca7c4e8cd)

As you can see the "Last modified time" is Nov 2022.

As of now I have not found a good way to obtain the required data that I need to plot the graphs. So I'm currently stuck.

**Comment by madnight** [comment]
@serdar-irmak 

Thank you for mentioning https://github.com/github/innovationgraph. It appears to be a valuable source, as the data is directly provided by GitHub. However, they seem to have issues with bots, which might affect the accuracy of their current ranking. Please refer to my issue: https://github.com/github/innovationgraph/issues/40.

**Comment by serdar-irmak** [comment]
Thank you very much for your reply @madnight
