### ISSUE TITLE
Feature request: hash value in URL to select mode and data-range

### ISSUE THREAD

**Issue by kanaka** [madnight/githut#12]
It would be great to be able to link directly to a specific time-frame and mode. I think the best way to do this is in the hash value (i.e. "#year=2017,quarter=Q4,mode=pushrequests"). The advantage of the hash value over the query parameter is that the page javascript can update the hash value (using the history API) without requiring the page to reload.

**Comment by madnight** [comment]
Hi kanaka, your suggestion sounds sensible, i'll have a look how i can do that with react

**Comment by madnight** [comment]
Hi, kanaka i added URLs for every possible configuration (e.g. /stars/2014/1). I followed your suggestion and used react-router with the HashRouter and history PI to avoid page reloads.

**Comment by kanaka** [comment]
@madnight Awesome! It correctly switches the mode and quarter when I changed them on the page. However, I think the mode isn't quite working on load. When I browser to this URL:

https://madnight.github.io/githut/#/stars/2016/3

It does show the correct year and quarter but it always shows "pull requests".

**Comment by madnight** [comment]
Oh thats true, i'm going to fix this today

**Comment by madnight** [comment]
Okay should be correct now.
