### ISSUE TITLE
display more attributes?

### ISSUE THREAD

**Issue by RichMorin** [madnight/githut#19]
I'd like to be able to display more attributes, including number of authors, projects, files, lines of code, etc. Please consider extending the site in this direction.

**Comment by madnight** [comment]
I`m limited by the dataset. The dataset is huge (several terabytes), but it only contains the following 14 distinct github event types:
```sql
SELECT DISTINCT type FROM githubarchive.month.201507 LIMIT 1000
```
```
MemberEvent
ForkEvent
WatchEvent
PublicEvent
IssueCommentEvent
CommitCommentEvent
PushEvent
IssuesEvent
GollumEvent
ReleaseEvent
DeleteEvent
PullRequestEvent
PullRequestReviewCommentEvent
CreateEvent
```

That is only a proper subset of the available ones, see https://developer.github.com/v3/activity/events/types/

**Comment by RichMorin** [comment]
Thanks for the informative reply. I'm only seeing data for Q2/12 through Q4/14. Is this all the data you have or do I need to do something to get a different range of dates?

**Comment by madnight** [comment]
As of now, you should be able to see 2012/Q2 till 2019/Q2 in the chart and 2014/Q1 to 2019/Q2 in the table.
