### ISSUE TITLE
Q: Does PR counts as Push too?

### ISSUE THREAD

**Issue by xged** [madnight/githut#20]

**Comment by madnight** [comment]
Nope, a PullRequest is a GitHub APIv3 PullRequestEvent: https://developer.github.com/v3/activity/events/types/#pullrequestevent that is defined as:

> Triggered when a pull request is assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked or when a pull request review is requested or removed.

And a Push is a GitHub APIv3 PushEvent https://developer.github.com/v3/activity/events/types/#pushevent that is defined as:

> Triggered on a push to a repository branch. Branch pushes and repository tag pushes also trigger webhook push events.


As you can see these events are complete distinct.
