### ISSUE TITLE
safe selected Languages

### ISSUE THREAD

**Issue by lucsoft** [madnight/githut#24]
doesn't need to be in localstorage just in the current window so when switching to stuff like stars it stores the languages

**Comment by tjpalmer** [comment]
I have the same request, if I understand it correctly. That is, when I switch the metric, the selected languages should stay selected.

**Comment by dmnd** [comment]
FYI #22 took care to ensure language selections persisted but a simpler implementation was merged (445071d3280fb6e85953ad0b8d0bb486e3e52436)

**Comment by madnight** [comment]
I think this issues has been fixed in the meantime. I cannot find any localstorage usage in the current master version.
