### ISSUE TITLE
Why are the results so different than octoverse? 

### ISSUE THREAD

**Issue by LifeIsStrange** [madnight/githut#28]
Go at the 4 place??????
It isn't even visible on the leaderboards of the octoverse

https://octoverse.github.com/#top-languages

Please explain!

**Comment by madnight** [comment]
I guess that they use a different method and/or different dataset to calculate the ranking. I use Pull Request or Pushes or Stars or Issues per quarter as metric with the public GitHub dataset on google big query as data source.

**Comment by LifeIsStrange** [comment]
Thank you, maybe they use private (commercial) github repositories stats too instead of just open source?

**Comment by madnight** [comment]
yup, that also may very well be possible
