### ISSUE TITLE
Run locally

### ISSUE THREAD

**Issue by blegat** [madnight/githut#3]
Is it possible to run Githut locally ? When I try it complains that it does not have the files `toplang-2016-12.json` and `LangTable.styl`

**Comment by madnight** [comment]
jup sorry, i forgot to add them yesterday, this are the new files that i add for the table feature
https://github.com/madnight/githut/commit/e1c1619842597268be9e6667df3d004197b80736

**Comment by blegat** [comment]
Thanks :)
