### ISSUE TITLE
Add newer GitHub supported languages

### ISSUE THREAD

**Issue by Adobe-Android** [madnight/githut#34]
Add newer GitHub supported languages like 
Zig (https://github.com/github/linguist/pull/4005),
Odin (https://github.com/github/linguist/pull/4676)

https://github.com/github/linguist/blob/master/grammars.yml

**Comment by madnight** [comment]
I use the public github big query dataset as source for the graph and the table. As soon as these languages (or any other new languages on github) makes it into the official dataset and into the top 50, they will automatically show up in the graph and table at the next quarterly update.
