### ISSUE TITLE
Add "number of unique comitters" metric

### ISSUE THREAD

**Issue by vincentdephily** [madnight/githut#38]
This is probably a bit more resource-intensive to compute than the other metrics, but I think it would be a very interesting additional perspective. You could do the same for issue comments, PRs, and stars, but I don't know if it's worth the trouble.

I tried to write the corresponding query, but got confused pretty quickly :/

**Comment by madnight** [comment]
I agree that this metric would be quite interesting, but yes I have to check if I'm able to get the required data from the GitHub dataset (with the BigQuery free plan).

**Comment by madnight** [comment]
> I tried to write the corresponding query, but got confused pretty quickly :/

Me 2. I think the problem is that the queries are already very complex and that the GitHub dataset is not in a easy consumable format for this kind of analysis. 

I will close this Issue for now, but I'm open to Pull Requests if someone finds an easy/good solution.
