### ISSUE TITLE
2021/Q1 data is probably incorrect

### ISSUE THREAD

**Issue by renom** [madnight/githut#42]
1. In pushes, stars and issues, all the percentage changes are negative.
2. Some of the trends are incorrect, for example Elixir in pull requests or Groovy in pushes.

**Comment by madnight** [comment]
You're right. After running the update script I just checked pull request, which seems to be fine. But the other metrics seems to be wrong. I will investigate that.

**Comment by madnight** [comment]
I had some API errors (temporary outage or network problems) while performing the update script, so I retried it several times and it seemed to work. However, the retry has caused the script to add the 2021/Q1 data multiple times to some of the datasets. This commits removes the duplicated data from the dataset.

https://github.com/madnight/githut/commit/5ee3cbb81138509d37a02ca716e47433b13cd179

**Comment by madnight** [comment]
Pull Requests, Stars and Issues seems to be correct now, but the Pushes looks strange. I don't think that this is a problem of the update script, but rather that this is the actual number of JavaScript pushes returned by the query. I will log in to google big query and manually check that result.

**Comment by madnight** [comment]
Goolge Big Query console confirms:

**Comment by madnight** [comment]
> Some of the trends are incorrect, for example Elixir in pull requests or Groovy in pushes.

No, it is correct, but a bit weird. The trend indicator evaluates YoY rank shifts. Groovy is up from rank 19 to rank 18, while still being down in overall percentage of pull request, which is possible.
