### ISSUE TITLE
Add Go to the chart at https://madnight.github.io/githut/

### ISSUE THREAD

**Issue by udhos** [madnight/githut#5]
Add Go to the chart at https://madnight.github.io/githut/

**Comment by madnight** [comment]
@udhos good point, i should point that out in the explanation text

The chart is calculated over the time period from 2012/Q2 until 2016/Q4 and shows the TOP 10 Languages based on that history. Go is relatively new in the TOP 10. The ranking table is based on the latest dataset 2016/Q4 (while the trend is calculated as diff from 2015/Q4). So new languages can pop up in the top 10 (table), but won't appear immediately in the history based chart. However if a new language will constantly stay (for some years) in the top 10, it will also show up in the chart and replace a language that dropped out of the top 10.

**Comment by madnight** [comment]
Updated description text to explain this behaviour https://github.com/madnight/githut/commit/2adca03d4cc70aaa33cb5c4dd2c568c6c571ec3d
