### ISSUE TITLE
question about table "github_repos.languages"

### ISSUE THREAD

**Issue by RainieYYY** [madnight/githut#55]
Hi, may I ask a question about the bigquery pulic databases?
I checked the number of distinct "repo.name" of PullRequest events in table "githubarchive.year.2020", and got the number 8,752,017, which is much larger than the number of table "bigquery-public-data.github_repos" rows 3,331,762.
Did I have anything wrong or is the table "github_repos.languages" imcomplete?
![image](https://user-images.githubusercontent.com/87684525/127630888-b2cc6af0-8caf-451e-b027-cf7242ce103e.png)

**Comment by madnight** [comment]
Hey RainieYYY,

yes it's very possible that the datasets on big query are not complete. According to Wikipedia, 

> As of January 2020, GitHub reports having over 40 million users[11] and more than 190 million repositories[12] (including at least 28 million public repositories),[13]

GitHub as over 28 million public repositories. I guess that the public datasets have some filters for things like empty repositories or repositories where GitHub couldn't determine the language (e.g. binary files). Hence, we sample over a subset, the data that is publicly available on big query that is.

If you have any suggestions on how to improve the query that I use, feel free to suggest a better query, e.g. one that samples over more repositories.

**Comment by RainieYYY** [comment]
I tried to download files from github API to get all the data, but that would take a very long time for me... for now, i have no idea about how to sample over more repositories with language information from bigquery public data. Thank you for your reply anyway, i will keep working on it. : )
