### ISSUE TITLE
Download Data

### ISSUE THREAD

**Issue by codergautam** [madnight/githut#57]
Add an option to be able to download data as csv

**Comment by JeremyLARDENOIS** [comment]
Hello, I went to pass, i love your project. I searched a little for a way to do it and I found this project that can help you: <https://github.com/zemirco/json2csv>. Don't hesitate if you need help. Have a nice day :slightly_smiling_face:

**Comment by madnight** [comment]
Hi Jeremy thanks for your interest in the project. Yes, this library looks good and it shouldn't be too hard to integrate. Would you mind a pull request?

**Comment by JeremyLARDENOIS** [comment]
No problem. Yes, I would. If I understood, I add this to `scripts/query.js`. Just one question to begin, how can I test that it works?

**Comment by madnight** [comment]
The website can be started locally with `npm run dev`.

**Comment by JeremyLARDENOIS** [comment]
up, i made it work, want just a script to transform json ? or do you want a button on the website that ask if you want a zipfile wif csv or json ?

**Comment by madnight** [comment]
A button on the website would be better, as it is more user friendly.
