### ISSUE TITLE
Make all categories (PR's, Stars, Issues, etc) visible options

### ISSUE THREAD

**Issue by rattrayalex** [madnight/githut#6]
It's not clear what I'm viewing now (am I *viewing* stars, or does clicking "stars" bring me there?) and it would be nice to be able to move between multiple options. 

By the way, thanks very much for putting this together!

**Comment by madnight** [comment]
@rattrayalex true i should make that more clear, you always watching the data that the button currently shows

So if the button says "Stars" you're watching the Star based chart and table.

**Comment by blegat** [comment]
By the way, it would also be useful to add the meaning of the symbols `<` `<<`, ...

**Comment by madnight** [comment]
@blegat you talk about the trend right?

**Comment by blegat** [comment]
Yes the trend :)

**Comment by madnight** [comment]
@blegat https://github.com/madnight/githut/commit/c5f1e098535a2b600424ef1fc8d2897b1accbd6f?short_path=765ddbb#diff-765ddbbabb5399731056646baa7112e7

**Comment by madnight** [comment]
@rattrayalex 
https://github.com/madnight/githut/commit/de135e8e45fa1777ae8a6a72f6e6980cd6f7e6e1

**Comment by rattrayalex** [comment]
Nice! Looking forward to seeing this go out!
