### ISSUE TITLE
When will 22Q1 come?

### ISSUE THREAD

**Issue by vuslatx** [madnight/githut#78]
When i look statics, i see 2021/4 last on madnight.github.io. We've left 22Q1 behind, but it's still not there. When will 22Q1 come? Thanks..

**Comment by madnight** [comment]
Ah your right. Damnit forgot about it. It will come now, give me a sec.

**Comment by madnight** [comment]
Done https://github.com/madnight/githut/commit/8a4092d049355acea3b572024cd4816afb78ebf7

**Comment by vuslatx** [comment]
> Ah your right. Damnit forgot about it. It will come now, give me a sec.

thanks but there is a mistake in pushes sort. c#'s persentage is %64 increased.

**Comment by madnight** [comment]
Interesting, as far as I can see that's not an error of the application, there has been 2962058 C# pushes in Q1 according to the data from github. Seems to be a weird outlier, maybe some bot.

**Comment by vuslatx** [comment]
> 

thank you for be interested in.

**Comment by vuslatx** [comment]
> 

Don't rush. Maybe the reason will reveal in the future. I have no doubt that you will do best.

**Comment by madnight** [comment]
@vuslatx 

I found that bot accounts like dependabot are the reasons for the incredible amounts of pushes. I decided to filter out bot accounts from now on (from 2022/Q1). 

https://github.com/madnight/githut/commit/1334a1e4b3f514f2455102ca23b63a039def307f

I reuploaded the 2022/Q1 dataset without bot accounts: https://github.com/madnight/githut/commit/80dcced5d3087894d840dc5aff80e50f9f551872

And I applied a fix for JS pushes for 2021/Q3 and Q4 without bots.
https://github.com/madnight/githut/commit/97e3731cd0100d69182f5dcb353445c505567101

It would be possible to recompute the complete history without bots, but this would exceed my Google Big Query Quota. Hence, I will leave the old datasets as they are for now and just continue without bot events.

**Comment by vuslatx** [comment]
> @vuslatx
> 
> I found that bot accounts like dependabot are the reasons for the incredible amounts of pushes. I decided to filter out bot accounts from now on (from 2022/Q1).
> 
> [1334a1e](https://github.com/madnight/githut/commit/1334a1e4b3f514f2455102ca23b63a039def307f)
> 
> I reuploaded the 2022/Q1 dataset without bot accounts: [80dcced](https://github.com/madnight/githut/commit/80dcced5d3087894d840dc5aff80e50f9f551872)
> 
> And I applied a fix for JS pushes for 2021/Q3 and Q4 without bots. [97e3731](https://github.com/madnight/githut/commit/97e3731cd0100d69182f5dcb353445c505567101)
> 
> It would be possible to recompute the complete history without bots, but this would exceed my Google Big Query Quota. Hence, I will leave the old datasets as they are for now and just continue without bot events.

good work. thank you. Is 22Q2 coming next week?

**Comment by madnight** [comment]
@vuslatx Problem is that i used all my available quota for this month for the bot account removal thing. So I have to wait until next month before I can run the query for 22Q2.
