### ISSUE TITLE
Update README.md with 2017/Q1 data

### ISSUE THREAD

**Issue by udhos** [madnight/githut#8]
How to re-generate the image displayed in the README.md ?
I noticed README.md includes Go while https://github.com/madnight/githut does not.

**Comment by madnight** [comment]
thats correct, the screenshot in the readme.md was from an very early version

as you can see the early Go values are near zero,  Go was shown before i decided to do it as described:
> The language percentage distribution in the line chart shows the top 10 languages since 2012/Q2. The ranking table shows the top 50 langauges based on the last quarter, while the trend is calculated as difference from the same quarter of the year before. 

and Go is no top 10 language over this time period 

i will update the screenshot

**Comment by madnight** [comment]
screenshot updated
