### ISSUE TITLE
missing abscissa

### ISSUE THREAD

**Issue by nbehrnd** [madnight/githut#80]
Assuming the chart is updated in regular intervals, _reading_ the plot would be greatly facilitated if there were a time line included.

As illustration, I merged the current plot with the abscissa provided/used by [Tiobe index](https://www.tiobe.com/tiobe-index/):

![pattern_with_abscissa](https://user-images.githubusercontent.com/19709084/174891777-5be116c2-d361-4ac0-b45b-e3315bf8d5b2.png)

Maybe you did not start to record the popularity of the programming languages by 2002, which would justify a different limit to the left hand side.  Then maybe you can use a finer scale; e.g. large tics with annotation of the year, and shorter ones of the quarters/months in between without an annotation -- just like the scale on a thermometer.

**Comment by madnight** [comment]
I added the time line (x-axis values).
