### ISSUE TITLE
Show absolute numbers?

### ISSUE THREAD

**Issue by casperisfine** [madnight/githut#88]
Hi, thanks for this.

If I may, I think showing only relative weight of each language isn't as interesting as the absolute counts could be.

For example right now you see Javascript "declining" since 2017-ish, but that doesn't tell us whether there is less JavaScript related activity on GitHub, or whether Javascript activity is still growing, but less than other languages.

I'm really bad at react, but from what I managed to figure out, all these percentages are computed from raw absolute counts, so the data is there already.

**Comment by madnight** [comment]
There's now a download button on the page where you can download and check the raw data in absolute values, but for comparison in the chart and table I find it better to compare the popularity in relative terms (percentage).
